php-5.4.45-fpm/Dockerfile

Build ok -> https://hub.docker.com/r/profideo/php-5.4.45-fpm/builds/bg6wwe2m5ksqbxjtpzhiu2q/

Enable php intl extensio in php-5.4.45-fpm

---

php-5.4.45-fpm/Dockerfile

Build OK https://hub.docker.com/r/profideo/php-5.4.45-fpm/builds/bzlkt3t2netzzjw2ztfmsyo/

Improve bcmath install in php-5.4.45-fpm

---

php-5.6.20-fpm/Dockerfile

Build OK https://hub.docker.com/r/profideo/php-5.6.20-fpm/builds/bus8gpcuoqxytvt8szebmfc/

Install php intl extension in php-5.6.20-fpm

---

php70-nginx/Dockerfile
php71-nginx/Dockerfile

Builds OK :
https://hub.docker.com/r/profideo/php70-nginx/builds/
https://hub.docker.com/r/profideo/php71-nginx/builds/

Update node to 8 on php71 and php70

---

php70-nginx/files/nginx.conf
php71-nginx/files/nginx.conf

To work with customer file workflow server name
Builds OK :
https://hub.docker.com/r/profideo/php70-nginx/builds/
https://hub.docker.com/r/profideo/php71-nginx/builds/

Update nginx conf

---

php70-nginx/Dockerfile

Build OK https://hub.docker.com/r/profideo/php70-nginx/builds/bx8jopfjluks4anryymeeaa/

Install php zip extension in php70-nginx

---

php70-nginx/Dockerfile
php70-nginx/files/supervisord.conf

Build OK -> https://hub.docker.com/r/profideo/php70-nginx/builds/b8hbwfhz6piux5w4fvqy3jw/

Launch freshclam as daemon in php70-nginx

---

php71-nginx/Dockerfile

Build OK -> https://hub.docker.com/r/profideo/php71-nginx/builds/btt2md3cfhzltndfzyfm297/

Add php extensions and clamav in php71-nginx

---

php71-nginx/files/supervisord.conf

Build OK -> https://hub.docker.com/r/profideo/php71-nginx/builds/b7b839dqwwkqcxke4wxwuqm/

Run clamav with supervisor in php71-nginx

---

php71-nginx-dev/Dockerfile
php72-nginx-dev/Dockerfile

Builds OK :
https://hub.docker.com/r/profideo/php71-nginx-dev/builds/bc5c3vsfcpjebrrprv7zbzw/
https://hub.docker.com/r/profideo/php72-nginx-dev/builds/bfabjvpbnwdip8jamdylrkf/

Enable xdebug in php71-nginx-dev and php72-nginx-dev

---

php71-nginx-dev/Dockerfile
php72-nginx-dev/Dockerfile

Reverts Profideo/docker-images#30

Revert "Enable xdebug in php71-nginx-dev and php72-nginx-dev"

---

php71-nginx/Dockerfile
php71-nginx/files/php.ini
php71-nginx/files/php/ext/opcache.ini
php72-nginx/Dockerfile
php72-nginx/files/php.ini
php72-nginx/files/php/ext/opcache.ini

Reverts Profideo/docker-images#31
Tests on https://github.com/Profideo/customer-file-workflow fails with it.

Revert "Enable opcache in php71-nginx and php72-nginx"

---

php71-nginx-dev/Dockerfile
php72-nginx-dev/Dockerfile

Use "-Dwebdriver.chrome.driver=/opt/chromedriver" option when launch selenium jar

Remove chromedriver path set in PATH env var

---

php72-apache-dev/Dockerfile

Build OK https://hub.docker.com/r/profideo/php72-apache-dev/builds/bvpgfhc59q84pbrmprmhyzr/

Update php72 apache dev

---

php72-apache-dev/Dockerfile

Build OK :
https://hub.docker.com/r/profideo/php72-apache-dev/builds/bjyhcajyjt9r7nxpszsslqr/
Before merge, put base branch to master when PR of base branch is merged with master.

 Upgrade chrome and chromedriver in php72-apache-dev 

---

php72-apache-dev/Dockerfile

Build OK https://hub.docker.com/r/profideo/php72-apache-dev/builds/bxuqowbsvtysdv6mjsyspmm/

Update selenium version in php72-apache-dev

---

php72-apache-dev/Dockerfile

Build OK : https://hub.docker.com/r/profideo/php72-apache-dev/builds/beyaenych4y3yjfjbdejq2n/

Upgrade chrome and chromedriver in php72-apache-dev

---

php72-apache-dev/Dockerfile

Build OK : https://hub.docker.com/r/profideo/php72-apache-dev/builds/bp4cvbupfaeterjetx5bx6d/

Upgrade selenium version used in php72-apache-dev

---

.gitattributes
install.sh
php72-apache-dev/Dockerfile
php72-apache-dev/files/install-java.sh
php72-apache-dev/files/jdk-8u211-linux-x64.tar.gz

We had error in previous installation saying that oracle-java8-installer is not found.

Change java installation in php72-apache-dev

---

.gitattributes
php72-apache-dev/Dockerfile
php72-apache-dev/files/jdk-8u211-linux-x64.tar.gz

Does not work when it is versioned

Remove jdk in php72-apache-dev and download it instead

---

php73-apache/Dockerfile

Build OK https://cloud.docker.com/u/profideo/repository/registry-1.docker.io/profideo/php73-apache/builds/0b5a2556-b06c-4bb1-8eaf-70edec307309

Fix node installation in php73-apache

---

php73-apache-dev/Dockerfile

Does not work with last version

Downgrade chromedriver in php73-apache-dev

---

php73-apache/Dockerfile

| Q                           | A
| --------------------------- | --------------------------------------
| Fixed issue(s) link(s)      | http://tickets.lesdossiers.com/issues/36169
| Bug fix?                    | no
| New feature?                | no
| Dependencies with other PRs | -
| Testing guidelines          | -
| Deployment guidelines       | -

[36169] Downgrade nodejs version to 6.x

---

php73-apache/Dockerfile

Upgrade nodejs in php73 apache
